const types = {
    SET_IS_ELECTRON: 'SET_IS_ELECTRON',
    GET_SERVICE_PORTS_PENDING: 'GET_SERVICE_PORTS_PENDING',
    GET_SERVICE_PORTS_SUCCESS: 'GET_SERVICE_PORTS_SUCCESS'
};

export default types;
